basePath: /api
definitions:
  api.Branch:
    properties:
      id:
        type: string
      merchantId:
        type: string
      municipality:
        type: string
      name:
        type: string
      street:
        type: string
    type: object
  api.Merchant:
    properties:
      category:
        type: string
      id:
        type: string
      municipality:
        type: string
      name:
        type: string
      street:
        type: string
    type: object
  api.Receipt:
    properties:
      date:
        type: string
      description:
        type: string
      entries:
        items:
          $ref: '#/definitions/api.ReceiptEntry'
        type: array
      id:
        type: string
      merchantId:
        type: string
      transactionId:
        type: string
    type: object
  api.ReceiptEntry:
    properties:
      id:
        type: string
      quantity:
        type: integer
      title:
        type: string
      value:
        type: string
      vatRate:
        type: number
    type: object
  api.Transaction:
    properties:
      date:
        type: string
      description:
        type: string
      iban:
        type: string
      id:
        type: string
      purpose:
        type: string
      userid:
        type: string
      value:
        type: number
      valutaDate:
        type: string
    type: object
info:
  contact: {}
paths:
  /branches:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            items:
              $ref: '#/definitions/api.Branch'
            type: array
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get all branches
      tags:
      - Branch
    post:
      consumes:
      - application/json
      parameters:
      - description: Add Branch
        in: body
        name: Branch
        required: true
        schema:
          $ref: '#/definitions/api.Branch'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/api.Branch'
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Create branch
      tags:
      - Branch
  /branches/{id}:
    get:
      parameters:
      - description: Branch Id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/api.Branch'
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get single branch by its id
      tags:
      - Branch
  /merchants:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            items:
              $ref: '#/definitions/api.Merchant'
            type: array
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get all merchants
      tags:
      - Merchant
    post:
      consumes:
      - application/json
      parameters:
      - description: Add Merchant
        in: body
        name: Merchant
        required: true
        schema:
          $ref: '#/definitions/api.Merchant'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/api.Merchant'
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Create merchant
      tags:
      - Merchant
  /merchants/{id}:
    get:
      parameters:
      - description: Merchant Id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/api.Merchant'
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get single merchant by its id
      tags:
      - Merchant
  /receipts:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            items:
              $ref: '#/definitions/api.Receipt'
            type: array
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get all receipts
      tags:
      - Receipt
    post:
      consumes:
      - application/json
      parameters:
      - description: Add Receipt
        in: body
        name: Receipt
        required: true
        schema:
          $ref: '#/definitions/api.Receipt'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/api.Receipt'
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Create receipt
      tags:
      - Receipt
  /receipts/{id}:
    get:
      parameters:
      - description: Receipt Id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/api.Receipt'
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get single receipt by its id
      tags:
      - Receipt
  /transactions:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            items:
              $ref: '#/definitions/api.Transaction'
            type: array
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get all transactions
      tags:
      - Transaction
    post:
      consumes:
      - application/json
      parameters:
      - description: Add Transaction
        in: body
        name: Transaction
        required: true
        schema:
          $ref: '#/definitions/api.Transaction'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/api.Transaction'
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Create transaction
      tags:
      - Transaction
  /transactions/{id}:
    get:
      parameters:
      - description: Transaction Id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/api.Transaction'
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get single transaction by its id
      tags:
      - Transaction
swagger: "2.0"
